version: "3.9"
services:
  securityapp:
    build:
      context: .
      dockerfile: Dockerfile
    image: securityapp:3.0
    ports:
      - "80:5000"
    restart: always
    networks: 
      - webnet
networks:
  webnet: