apiVersion: apps/v1
kind: Deployment
metadata:
  name: security
  labels:
    app: app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: securityapp
        image: securityapp:3.0
        ports:
        - containerPort: 5000